name: 'Setup Python Dev'
description: 'Set up Python development environment with uv'

runs:
  using: 'composite'
  steps:
    - name: Setup uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: uv sync --dev
      shell: bash
