name: Setup Python Environment (Dev)
description: Sets up Python with uv and installs dev dependencies

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setup-uv
    - name: "Set up Python"
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"
    - name: Install dependencies
      run: |
        uv sync --extra dev
      shell: bash
