name: Build and Publish Python Wheel

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: '3.12'

          - name: Install build dependencies
            run: python -m pip install --upgrade pip build

          - name: Build wheel
            run: python -m build --wheel

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: python-wheel
              path: dist/*.whl
