name: CI UI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.13.7"
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ui/.dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install lcov
      - name: Install Flutter dependencies
        run: |
          cd ui
          flutter pub get
      - name: Test with flutter test
        run: |
          cd ui
          flutter test --coverage
      - name: Generate coverage report
        run: |
          cd ui
          genhtml coverage/lcov.info -o coverage/html
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: ui/coverage/html
